# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:21
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField(help_text='必須! 1に近いほど上に表示されます。', verbose_name='ID')),
                ('memname', models.CharField(help_text='フルネームでお願いします', max_length=30, verbose_name='名前')),
                ('position', models.CharField(max_length=30, verbose_name='役職')),
                ('itself', models.TextField(help_text='軽く自己紹介 - 学部学科,呼び名,趣味なんでもいいです。', max_length=200, verbose_name='自己紹介')),
                ('image', models.ImageField(blank=True, help_text='画像は任意で', storage=django.core.files.storage.FileSystemStorage(location='static/media/'), upload_to='memberphoto/', verbose_name='画像')),
            ],
        ),
    ]
