# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlist',
            name='display',
            field=models.BooleanField(default=True, verbose_name='表示/非表示'),
        ),
    ]
