# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-18 06:49
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='kta40thx/static/media/memberphoto'), upload_to='memberphoto', verbose_name='画像'),
        ),
    ]
