# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20160322_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlist',
            name='orderid',
            field=models.IntegerField(default=1, help_text='必須! 1に近いほど上に表示されます。', verbose_name='ID'),
            preserve_default=False,
        ),
    ]
