# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20160326_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlist',
            name='itself',
            field=models.TextField(help_text='軽く自己紹介 - 学部学科,呼び名,趣味なんでもいいです。', max_length=200, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='memname',
            field=models.CharField(help_text='フルネームでお願いします', max_length=30, verbose_name='名前'),
        ),
    ]
