# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20160329_2000'),
        ('member', '0002_memberlist_display'),
    ]

    operations = [
    ]
