# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planmonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_month', models.CharField(blank=True, choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], max_length=3, verbose_name='月')),
                ('evently', models.CharField(blank=True, max_length=50, verbose_name='イベント内容')),
                ('description', models.CharField(default="複数入力する場合は間を','で区切るように", max_length=80, verbose_name='概要')),
            ],
        ),
        migrations.CreateModel(
            name='Planyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_year', models.CharField(choices=[('2016', '2016年度'), ('2017', '2017年度'), ('2018', '2018年度'), ('2019', '2019年度'), ('2020', '2020年度'), ('2021', '2021年度'), ('2022', '2022年度'), ('2023', '2023年度'), ('2024', '2024年度'), ('2025', '2025年度'), ('2026', '2026年度'), ('2027', '2027年度'), ('2028', '2028年度'), ('2029', '2029年度'), ('2030', '2030年度'), ('2031', '2031年度'), ('2032', '2032年度'), ('2033', '2033年度'), ('2034', '2034年度'), ('2035', '2035年度'), ('2036', '2036年度')], help_text='年度は他と被らないようにしてください。', max_length=5, verbose_name='年度')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('up_date', models.DateTimeField(auto_now=True, verbose_name='編集日時')),
            ],
        ),
        migrations.AddField(
            model_name='planmonth',
            name='planyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Planyear'),
        ),
    ]
