# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.CharField(blank=True, max_length=30, verbose_name='活動日時')),
                ('active_place', models.CharField(blank=True, max_length=30, verbose_name='活動場所')),
                ('member_numbers', models.IntegerField(blank=True, help_text='大体でいいです。', verbose_name='会員数')),
                ('member_charge', models.CharField(blank=True, help_text='年会費,月会費など', max_length=30, verbose_name='会費')),
                ('address_place', models.TextField(blank=True, max_length=100, verbose_name='住所')),
                ('contact_to', models.CharField(blank=True, help_text='もしあれば。', max_length=30, verbose_name='連絡先')),
                ('mail_address', models.EmailField(blank=True, help_text='必ず連絡の取れるもので。', max_length=254, verbose_name='メールアドレス')),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=30, verbose_name='関連リンク名')),
                ('link_url', models.URLField(blank=True, verbose_name='URL')),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footer.Footer')),
            ],
        ),
    ]
