# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_auto_20160323_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='related',
            name='link_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='関連リンク名'),
        ),
        migrations.AlterField(
            model_name='related',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
