# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_auto_20160323_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='member_charge',
            field=models.CharField(blank=True, help_text='年会費,月会費など', max_length=30, verbose_name='年会費'),
        ),
    ]
